#!/usr/bin/env bash
# installs nginx on a remote server and configures it
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
sudo chown -R $USER:$USER /var/www
echo 'Holberton School' > /var/www/html/index.nginx-debian.html
sudo service nginx start
